### ISSUE TITLE
Research Polymer elements vs Foundation elements

### ISSUE THREAD

**Issue by bobvanluijt** [dorel/digital-design#4]
Would be awesome if we can see the following
1. Overview of Polymer vs. Foundation elements.
2. Review Foundation Grid vs. [Polymer Grid](https://github.com/The5heepDev/iron-grid)
3. Based on above answer (if Foundation Grid is better) can we integrate the Foundation as a Polymer element?

**Comment by StudioSpindle** [comment]
**Foundation 6 Elements**

**Layout**
Grid
Flex Grid
Forms
Visibility Classes
Float Classes
Flexbox

**Typography**
Base Styles
Helper Classes

**Controls**
Button
Button Group
Close Button
Slider
Switch

**Libraries**
Motion UI
Panini

**Navigation**
Overview
Menu
Dropdown Menu
Drilldown Menu
Accordion Menu
Top Bar
Responsive Navigation
Magellan
Pagination
Breadcrumbs

**Containers**
Accordion
Callout
Dropdown
Media Object
Off-canvas
Reveal
Table
Tabs

**Media**
Badge
Flex Video
Label
Orbit
Progress Bar
Thumbnail
Tooltip

**Comment by StudioSpindle** [comment]
@bobvanluijt paper elements show the most similarities with foundation elements.
